### ISSUE TITLE
NoMethodError: undefined method `alias_method_chain' in Rails 5.1

### ISSUE THREAD

**Issue by EricOVGU** [a-ono/redmine_ckeditor#259]
Hello!
Is this plugin working with rails 5.1? I get this error when doing the rake task for migration:

NoMethodError: undefined method `alias_method_chain'  for Redmine::Export::PDF::ITCPDF:Class
Did you mean?  alias_method
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:7:in `block in included'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:6:in `class_eval'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:6:in `included'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:60:in `include'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:60:in `<module:RedmineCkeditor>'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:3:in `<top (required)>'

Thanks for answer!

**Comment by iceblove** [comment]
the same to mine.

Environment:
  Redmine version                3.4.4.devel
  Ruby version                   2.3.3-p222 (2016-11-21) [universal.x86_64-darwin17]
  Rails version                  5.1.4
  Environment                    production
  Database adapter               PostgreSQL

**Comment by tcjuan** [comment]
alias_method_chain is removed from Rails 5+. Yo need to use module/prepend .

**Comment by iceblove** [comment]
And how to use module/prepend to config redmine_ckeditor ? Any guide could be help, thanks.

**Comment by nanego** [comment]
Redmine 3.4.4 is not compatible with Rails 5.1. If you use the correct version of Rails for your version of Redmine, the ckeditor will work just fine.

**Comment by tcjuan** [comment]
I tis hard to rewrite alias_method_chain with  module/prepend style. Try to use 
gem 'alias_method_chain'  to keep it work is the easy way. 
But, I finally drop redmine_ckeditor plugin and integrated Ckeditor direct from java script source.
